apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: person-id-data
  labels:
    app: person-id
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
